platform :ios, '9.0'
inhibit_all_warnings!

# Disable sending stats
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'emplesMVC' do
    pod 'JSONModel'
    pod 'SDWebImage', '~>3.8.2'
    pod 'GoogleMaps'
    pod 'iCarousel'
    pod 'ZLSwipeableView'
    
    target 'emplesMVCTests' do
        inherit! :search_paths
        pod 'OCMock'
    end
end

#   Disable Code Coverage for objc Pod projects
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
        end
    end
end

