platform :ios, '9.0'
inhibit_all_warnings!

# Disable sending stats
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'emplesMVC' do
    pod 'JSONModel'
    pod 'SDWebImage', '~>3.8.2'
    pod 'GoogleMaps'
    pod 'iCarousel'
end
